In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [2]:
x <- 1 : 10
cat(x)
cat('Mean of x is',mean(x))
cat('Median of x is',median(x))
cat('variance of x is',var(x))
cat('Standard Deviation of x is',sd(x))

1 2 3 4 5 6 7 8 9 10Mean of x is 5.5Median of x is 5.5variance of x is 9.166667Standard Deviation of x is 3.02765

In [3]:
cat(x,'\n')
cat('Mean of x is',mean(x),'\n')
cat('Median of x is',median(x),'\n')
cat('variance of x is',var(x),'\n')
cat('Standard Deviation of x is',sd(x),'\n')

1 2 3 4 5 6 7 8 9 10 
Mean of x is 5.5 
Median of x is 5.5 
variance of x is 9.166667 
Standard Deviation of x is 3.02765 


In [5]:
x <-8+7
x

[1] 15

In [6]:
x <- "dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [7]:
x <- 23
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "numeric"

[1] "double"

[1] 1

NULL

In [8]:
x <- 23L
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "integer"

[1] "integer"

[1] 1

NULL

In [9]:
x <- 2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [10]:
x <- TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] TRUE

[1] "logical"

[1] "logical"

[1] 1

NULL

In [12]:
vector()

logical(0)

In [14]:
vector("character",length = 5)

[1] "" "" "" "" ""

In [15]:
character(5)

[1] "" "" "" "" ""

In [16]:
numeric(5)

[1] 0 0 0 0 0

In [17]:
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [20]:
x <- c(12,23,34,45,56)

In [21]:
x
class(x)

[1] 12 23 34 45 56

[1] "numeric"

In [22]:
x <- c(12L,23L,34L,45L,56L)
x
class(x)
length(x)

[1] 12 23 34 45 56

[1] "integer"

[1] 5

In [24]:
x <- c(TRUE,TRUE,FALSE,FALSE,TRUE)
x
class(x)
length(x)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [25]:
x <- c("Sarah","Tracy","Jon")
x
class(x)
length(x)

[1] "Sarah" "Tracy" "Jon"

[1] "character"

[1] 3

In [26]:
print("Elements in x below")
x
x <- c(x,"Annette")
print("Elements in z after adding new element")
x

[1] "Elements in x below"


[1] "Sarah" "Tracy" "Jon"

[1] "Elements in z after adding new element"


[1] "Sarah"   "Tracy"   "Jon"     "Annette"

In [27]:
print("Elements in x below")
x
x <- c(x,"Greg")
print("Elements in z after adding new element")
x

[1] "Elements in x below"


[1] "Sarah"   "Tracy"   "Jon"     "Annette"

[1] "Elements in z after adding new element"


[1] "Sarah"   "Tracy"   "Jon"     "Annette" "Greg"

In [30]:
a <- 1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [31]:
seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [32]:
seq(from = 1, to =10, by = 0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [33]:
1/0

[1] Inf

In [34]:
0/0

[1] NaN

In [35]:
exp(Inf)

[1] Inf

In [36]:
exp(-Inf)

[1] 0

In [37]:
Inf-Inf

[1] NaN

In [38]:
log(0)

[1] -Inf

In [39]:
log(1)

[1] 0

In [55]:
a <- c(1.7,"a")
a

[1] "1.7" "a"

In [41]:
b <- c(TRUE,2,3,FALSE)
b

[1] 1 2 3 0

In [44]:
c <- c("ab",TRUE)
c

[1] "ab"   "TRUE"

In [45]:
as.numeric("1")

[1] 1

In [48]:
as.numeric(c("45","56"))

[1] 45 56

In [49]:
as.complex(23)

[1] 23+0i

In [51]:
as.character(22)

[1] "22"

In [56]:
m <- matrix(nrow = 2,ncol = 2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [57]:
dim(m)

[1] 2 2

In [59]:
class(m)

[1] "matrix"

In [60]:
typeof(m)

[1] "logical"

In [63]:
m <- matrix(c(1:4),nrow =2,ncol = 2)
m
typeof(m)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] "integer"

In [64]:
dim(m)
class(m)


[1] 2 2

[1] "matrix"

In [65]:
m <- 1:10
print(m)
print(dim(m))
dim(m) <- c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [68]:
my_name <- readline(prompt="Enter name:")
my_age <- readline(prompt="Enter age:")
my_age <-as.integer(my_age)
print(paste("Hi,",my_name,"next year you will be",my_age+1,"years old."))

Enter name:subash
Enter age:19
[1] "Hi, subash next year you will be 20 years old."
